# Chapter 1 - The Golem of Prague

## 1.1 - Statistical Golems

"Golem" analogy to clay robots that just do what they're told without thinking, leading to carelessness. Common in statistics too, consider flowcharts with many different tests at the end. Need a more generalized approach (think engineering - don't start with building bridges, start with physics), rethinking inference as a set of strategies, not a set of tools.

## 1.2 - Statistical Rethinking

Many have approach that the objective of inference is to test null hypotheses, but science isn't described by falsification standard.

### Hypotheses are not models 
- Models can correspond to multiple hypotheses, multiple hypotheses to a model
- All models are false, so what does it mean to falsify a model?

Progression:
- Hypotheses - Statements
- Process Models - Causal structure model that formalize cause/effect relationships
- Statistical Model - Don't embody causal relationships; express associations among variables

How to get from statistical model back to process model? Derive a expected frequency distribution of some quantity - "statistic" from the causal model. Histogram, for example. Unfortunately, other models can imply the same statistical model, reinforcing the many-to-many relationships:

- Any statistical model can correspond to many process models
- Any hypothesis can correspond to multiple process models
- Any statistical model can correspond to multiple hypotheses

So what to do? If you have multiple process models that all make similar predictions, then you search for a description where the processes look different. 

### Measurement matters 
Logic of falsification is have hypothesis, look for observation. If not found, then hypothesis is false. If we formalize $H_0$ to "All swans are white", no number of observations can prove it, one observation disproves - powerful but prone to observation errors, and quantitative hypotheses have degrees of existence

**Observation Error** - Doubted observations, measurement/instrumentation error

**Continuous Hypotheses** - Not trying to disprove, but understand a distribution

### Falsification is consensual

Communities argue toward consensus about the meaning of evidence, can be messy

## 1.3 - Tools for Golem Engineering
If falsification isn't the way, we can model. Models then can be made to testing procedures, as well as designs, forecasts, and arguments. This text focuses on several tools:
- Bayesian Data Analysis
- Model comparison
- Multilevel models
- Graphical models


### Bayesian data analysis
Takes question in form of a model and uses logic to produce an answer in the form of probability distributions. Literally just counting how the data may look according to our assumptions. Compare to frequentest, which is defined by the frequencies of events in large samples, based on imaginary data resampling.

Bayesian approaches treat randomness as a property of information, not of the world.

### Model comparison and prediction
If multiple models, how to choose? Cross validation and information criteria.

Help in 3 ways: provide expectations of accuracy, give an estimate of overfitting, help spot influential observations

### Multilevel Models

Parameters all the way down - parameters support inference. Multiple levels of uncertainty feed into the next, a multilevel (hierarchical, random effects, varying effects, mixed effects) model. Help us with overfitting, by exploiting partial pooling, which can be used to adjust estimates for repeat sampling, imbalance, variation, and to avoid averaging.

Diverse models turn out to be multilevel: models for missing data (imputation), measurement, factor analysis, some time series models, and types of spatial and network regression are all special applications of multilevel.

Fitting and interpreting multilevel models can be harder than traditional

### Graphical Causal Models 

Statistical models are association engines, detect (not infer!) association between cause and effect. Due to overfitting though, causally incorrect models can make better predictions than causally correct ones, can't focus on just prediction.

So instead, causal model that can be used to design one or more statistical models for causal identification. "Graphical Causal Model" represents a causal hypothesis, the most simple being a Directed Acyclic Graph (DAG).


## 1.4 - Summary

4 parts to book

1. Bayesian inference (ch 2,3)
2. Multiple linear regression (ch 4-9)
3. Generalized linear models, with MCMC and maximum entropy (ch 9-12)
4. Multilevel models, specialized models (ch 13-17)


